(global-set-key (kbd "C-c C-d") 'export-theorem)
(global-set-key (kbd "C-c C-e") 'save-file-conventions1)
(global-set-key (kbd "C-c m") 'show-clusters-of-theorem)
(global-set-key (kbd "C-c C-SPC") 'extract-feature-theorems)
(global-set-key (kbd "C-c c") 'show-clusters)
(global-set-key (kbd "C-c e") 'extract-feature-theorems-dynamic)
(global-set-key (kbd "C-c d") 'show-clusters-dynamic)
(global-set-key (kbd "C-c a") 'change-algorithm-interactive)
(global-set-key (kbd "C-c g") 'change-granularity-interactive)
(global-set-key (kbd "C-c f") 'change-frequency-interactive)
(global-set-key (kbd "C-c i") 'change-iterative-interactive)
(global-set-key (kbd "C-c C-m") 'proof-assert-next-command-interactive3)
(global-set-key (kbd "C-c n") 'save-numbers)

